<footer class="fixed-bottom">
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
  <img class="logo"
     src="../assets/images/ebe8h8tq9942s4jh4ms5c8te3v.png"
     alt="" width="2%">
    <div class="collapse navbar-collapse" id="navbarNavDropdown text-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="./liste.php">Liste</a>
        </li>
        <li class="nav-item flex-end"> </li>
      </ul>
    </div>
    <div class="text-right text-white col-4"> Copyright &copy; 2021 </div>
  </div>
</nav>
</footer>
</body>
</html>