<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Liste Projet Purge</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>  
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  <script src="../assets/js/script1.js"></script>
</head>
<body>
<header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
  <img class="logo"
     src="../assets/images/ebe8h8tq9942s4jh4ms5c8te3v.png"
     alt="Grapefruit slice atop a pile of other slices" width="5%">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="liste.php"><h4>Liste</h4></a>
        </li>
      </ul>
    </div>
      <div class="nav-item dropdown ">
        <?php if(isset($_SESSION['utilisateurs'])){ ?>
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <h5>Bienvenue <?=$_SESSION['utilisateurs']['login'];?></h5>
          </a>
        <?php } ?>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <?php if(isset($_SESSION['utilisateurs']) && $_SESSION['utilisateurs']['role'] == 1){?>
            <li><a class="dropdown-item" href="inscription.php">Inscription</a></li>
            <?php } ?>
            <li><a class="dropdown-item" href="logout.php">Déconnexion</a></li>
          </ul>
        </div>
  </div>
</nav>
</header>